apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: poc-s3-application-enyrcpted-bucket
spec:
  name: poc-s3-application-enyrcpted-bucket
  encryption:
    rules:
    - bucketKeyEnabled: false
      applyServerSideEncryptionByDefault:
        sseAlgorithm: AES256
  versioning:
    status: Enabled